{
    "DEVICE_IDs": [
        "ea4326ba-a71d-46b8-8e72-6557d5f9f292"
    ],
    "SS_ID": "SS_ID_111",
    "START_TIME": "2023-09-14 00:00:00",
    "END_TIME": "2023-09-20 23:59:59",
    "timezone": "Australia/Victoria",
    "csv_directory": "./SS_ID_111",
    "sensors": [
        "applications_foreground",
        "applications_notifications",
        "battery",
        "bluetooth",
        "locations"
    ],
    "output_file": "./SS_ID_111_output.txt",
    "daily_output_dir": "./daily_description_SS_ID_111",
    "DISCARD_SYSTEM_UI": "true",
    "GOOGLE_MAP_KEY": "",
    "hierarchy_linkage": "complete", # longest distance between location clusters, complete=longest, single=shortest
    "night_time_start": "20", # Start of nighttime in 24-hour format, used for determining home location  
    "night_time_end": "4",  # End of nighttime in 24-hour format, used for determining home location  
}
