name: my_env # The environment name
channels:
  - conda-forge
  - defaults
dependencies:
  # Base Python and essential system libraries
  - python=3.13
  - pip
  
  # Scientific computing stack from conda
  - numpy
  - scipy
  - pandas
  
  # Additional conda packages for better performance
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  
  # Data visualization (install via conda to avoid build issues)
  - matplotlib
  - seaborn
  
  # Install remaining dependencies via pip
  - pip:
      # Scientific computing and machine learning
      - astropy
      - scikit-learn
      
      # Geographic and location processing
      - geopy
      - googlemaps
      
      # Configuration and time handling
      - PyYAML
      - pytz
